<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="20326" started-at="2021-05-22T23:33:31 IST" finished-at="2021-05-22T23:33:51 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="20326" started-at="2021-05-22T23:33:31 IST" finished-at="2021-05-22T23:33:51 IST">
      <class name="practice.AppiumFramework.FirstTest">
        <test-method status="PASS" signature="apiDemoTest()[pri:0, instance:practice.AppiumFramework.FirstTest@1d371b2d]" name="apiDemoTest" duration-ms="19735" started-at="2021-05-22T23:33:31 IST" finished-at="2021-05-22T23:33:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiDemoTest -->
        <test-method status="PASS" signature="dataProviderTest(java.lang.String)[pri:0, instance:practice.AppiumFramework.FirstTest@1d371b2d]" name="dataProviderTest" duration-ms="3" started-at="2021-05-22T23:33:50 IST" data-provider="InputData" finished-at="2021-05-22T23:33:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Hello]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataProviderTest -->
        <test-method status="FAIL" signature="dataProviderTest(java.lang.String)[pri:0, instance:practice.AppiumFramework.FirstTest@1d371b2d]" name="dataProviderTest" duration-ms="1" started-at="2021-05-22T23:33:50 IST" data-provider="InputData" finished-at="2021-05-22T23:33:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[@$%&@]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [@$%&@] but found [Hello]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [@$%&@] but found [Hello]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at practice.AppiumFramework.FirstTest.dataProviderTest(FirstTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataProviderTest -->
      </class> <!-- practice.AppiumFramework.FirstTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
